version: '3.8'

services:
  app:
    image: mercedes-helper:latest
    container_name: mercedes-helper-app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/production.db
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    volumes:
      - /opt/mercedes_search/data:/app/data
      - /opt/mercedes_search/uploads:/app/uploads
    restart: unless-stopped
    networks:
      - mercedes-net
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/vehicles"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: mercedes-helper-nginx
    ports:
      - "${HTTP_PORT:-8080}:80"
      - "${HTTPS_PORT:-8443}:443"
    volumes:
      - /opt/mercedes_search/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/mercedes_search/ssl:/etc/nginx/ssl:ro
      - /opt/mercedes_search/uploads:/var/www/uploads:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - mercedes-net

networks:
  mercedes-net:
    driver: bridge